server:
  port: 80
eureka:
  client:
    fetch-registry: true # 默认为true 是否从eureka中抓取注册信息
    register-with-eureka: false #是否向eureka注册自己被其他服务发现，默认为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/, http://eureka7002.com:7002/eureka/
